# 模型相关配置
model_name_or_path: "/data/name_disambiguation/model/BAAI/bge-m3"
padding_side: "right"
use_graph: false
dynamic_weight: false

# 数据相关配置
packing_size: 24
positive_num: 4
shuffle: false

# 训练流程控制
do_predict: false
resume_from_checkpoint: "/data/name_disambiguation/model/SNDPacking/checkpoint-1"
num_train_epochs: 40
save_steps: 100
save_total_limit: 200
evaluation_strategy: "steps"
eval_steps: 100
load_best_model_at_end: false
metric_for_best_model: "avg_f1"
remove_unused_columns: false
use_cluster_loss: true

# 优化器相关
learning_rate: 0.000008
warmup_ratio: 0.1
lr_scheduler_type: "cosine"

# 预测时聚类相关参数
db_min: 1
db_eps: 0.05

# 对比学习温度参数
temperature: 0.02
temperature_decay: 0.99
temperature_decay_step: 200

# 硬件/性能配置
per_device_train_batch_size: 1
per_device_eval_batch_size: 1
gradient_accumulation_steps: 1
bf16: true
deepspeed: "/data/name_disambiguation/configs/ds_configs/ds_zero_3_offload.json"

# 日志和输出
output_dir: "/data/name_disambiguation/model"
report_to: "wandb"
logging_steps: 1